apiVersion: v1
kind: Secret
metadata:
  name: cloudflare-dns-secret
stringData:
  api-token: ENC[AES256_GCM,data:cqFxTKX/KaodRdhDzTpoUR/hXkyBfZZIctnK+ByMCrjBiVJQQISqCA==,iv:pNUwg7GVeFtSMBAeysVR+iVXT5lwYHxjaaPcWO6Ypks=,tag:KNcUGDecHzovBIpnuS+BSA==,type:str]
sops:
  age:
    - recipient: age1apkw8x08jjevajqf39f5g3awkxk3u82c5l6r9y44h0slk9jlds3qvxkcnu
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBCYkFWbWtjUmpwSTRFajNQ
        VkFTT3hFOGg1YXRyOEVLa1Z5bjluQ252OTFjCm1YTUQ0bm5vd3JRWnFFTGdaNm5m
        K3dIbDVvdTBMYk56Zy91dy9RZ3J4S0kKLS0tIGw0bnNxeExXeC9lSWlnREU0NURW
        RzRIbUF4Tllib0N4SE95dUM0TklBQ00KlV4IKQILM9DS1S3hWhXaow0w6+3UUT3T
        DkQiDdr2M3uIpb/GB5Jm8itmmnM0C4J3oP//NgUChtuJoaK7m1Z93g==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-12-05T01:31:34Z"
  mac: ENC[AES256_GCM,data:CemxhaJ7UQrzUz8SqPUVFIZlDr5t9go7+TcjSNdCa1CZinAjeFw0QmEDFfMxXSzuEUcrVukFpSZQM1A9l/x1XqucJokJfkPtuQTTXvZyTjrwjgb0+JBC58ipjWvHtT9DhWAib/6LlMGEpPxNn8uMqNK9gBZWV3pyxtMXmIREDdM=,iv:25j+gtq4t6Q938ycBC1R/uvmx+Hns8shW7Rt29bmAC0=,tag:tAEjW8/Yf3cFEJcfR+NSxg==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
