apiVersion: v1
kind: Secret
metadata:
  name: cloudflare-dns-secret
stringData:
  api-token: ENC[AES256_GCM,data:Pcv/fJ2MFv+5NVtJiWIUjnrBBtprd0LjShWwxaTHn0NnJH/oGeHklw==,iv:G8wBj3yW4C0k8rF2Vg/NlyXpJgac9/vytR8/mJZaULs=,tag:RkCBGmXy40R5o62EmIIUZQ==,type:str]
sops:
  age:
    - recipient: age1apkw8x08jjevajqf39f5g3awkxk3u82c5l6r9y44h0slk9jlds3qvxkcnu
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBmK0xGNVBxbkU5U283ZStu
        Z1QyWGRodCtWZ1loV1hnRTY1dm1JY0l1UEhJCjlCdmt6L1VUUDJPNENmZFBTYzRJ
        RERJbElqcHRMUTlURkdvY2RhbENldTAKLS0tIDdab0dDZnpKOWViMUMvSU9RRCtk
        V0hTRnJwbEhJaFVjaDVCOTd5QnRoeWMK7JkKzzF9JDbr6TNMdJVaBTbP2x8fKy34
        v1rvS0GXOrhwtMihsuWRcftIdDvJ6v8GRaTFCNaOxx1fHlRCN6oNCw==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-12-05T00:28:13Z"
  mac: ENC[AES256_GCM,data:83mBNrVwrc/7k/IR1uB6YKgJ87UT2ssFkUhm+NN5Tw3TJ4Go72gAg0SEpuxswnmN9WoMmZNvYScAb/BhnM3IEaFf/bkHeHiUcGB2DEpl5tJnVNQYbUl3Y3hATC38Ruf7QwI2tSJsxrxP6lxI4hL8qsfE1c3jAP0iNXhtQvban1w=,iv:bKPgKx95R0WhFmrpGL2hnMRyIAW5g1VtkPcroHzD16o=,tag:KpzgD9WhLh5NzCZGE1Zitg==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
