apiVersion: v1
kind: Secret
metadata:
  name: cluster-secrets
stringData:
  SECRET_DOMAIN: ENC[AES256_GCM,data:h3cXpEtQ+6iS9mKRXZf1DFg=,iv:wqtX+ViGyptDDjGh78FDzbJnecQc3R0XEbAzaF29B0Q=,tag:47rKoXXNiemGiU+2enbonQ==,type:str]
sops:
  age:
    - recipient: age1apkw8x08jjevajqf39f5g3awkxk3u82c5l6r9y44h0slk9jlds3qvxkcnu
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB6aGl3bmF2azRNa0Zubkp1
        ZE1nS3FVOTBDMkJLcHZGOWgzTjZTdG1jSVdvCjdwWDJ6dkZ5Sld3TFRzZ0V2dEpa
        R3dNNVpBVGFubXc0b3hlVUZPWFRObGcKLS0tIFJtU1BkTVFiWVJFZkVUQm1sbk1h
        SmdQYjQ0alg0a0E0VWhvWGdlUXdzczgK6aprmMfcYXRrsZXNgcD67IicKeaLWceY
        Y34Z4/pRrQvkL6ScDbE+9U/GwXMdf3qQApt1UARj63I12aACf/YP2g==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-12-05T00:28:13Z"
  mac: ENC[AES256_GCM,data:JeVBm2/U5OU6YC9MGQ1sNsbshfNE9L9/WLgdXNwi1IDJtrAlW1anyPSY7rBmGByCiGfvaNUiLp7Z0Wcta8RykCx/+hGXdDC+t4+9Ja8dmzzgQfjcyj0u4PBCU3rjw5FtihgSgQpxgbJrjwiUq1oNY4kLrx0uP9//I0P4FJodpo0=,iv:NrtyurpoyVAw/dbrOKeA5s0t1aPR2iHT5zhkGvjUGS0=,tag:JzTplC/rrgt0bBvyWsAX4g==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
