apiVersion: v1
kind: Secret
metadata:
  name: cluster-secrets
stringData:
  SECRET_DOMAIN: ENC[AES256_GCM,data:CbHUGI7FpKfXSNdhL1A606Q=,iv:kgxsLgVew245yBr064tUk5i8Ymr8Uq+I+275Fzf/2gg=,tag:ns+BmkDsGJRlTRi7bb0NFw==,type:str]
sops:
  age:
    - recipient: age1apkw8x08jjevajqf39f5g3awkxk3u82c5l6r9y44h0slk9jlds3qvxkcnu
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBHMmE4K2FVTVFMNGtUSjl4
        WWg1QXJSeGdWV0ZxUTc1alAwNXhBZzNmVndJCkFPUTNXcno5dUM3ZjlvTUp0cE03
        aUpHZ2YrbmNqaEFYTUNYSy9RVW5jdmsKLS0tIGV4R0tSdVJIVU1JQTFVU1hEYW5X
        aE1Ncm5yTTB5dlBhalJ3ODBnZUhxN2sK3EftuP3+1XmNBok2+XT4IfFgmX0FmpAR
        SoAylNC3SibhF/OUaEAZoe/WJiApel06mzo7gUVzwAVYz6cSvhO4nA==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-12-05T01:26:55Z"
  mac: ENC[AES256_GCM,data:4K/crA5CUPfL5zo0azKw/Plmj1LqKgGReLpjRIiUwNfKh0IU7ctG+4tk3JJPDI92052nmJAaIrP9esFefHP2KMFGbu6rfyQKwpRxIs0tir2CRPWNdWKGsV20V8KEGvbAjrcYcwsIVp1TpKfLezDooST8CIlpHW6SBmxp2pUfLo4=,iv:QE/uQAczc4FiMXgRWto6dd0Au0PR1m5RGjFk7RSpsV8=,tag:wvW92D+A7Xw4lvX/XzyF/g==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
