apiVersion: v1
kind: Secret
metadata:
  name: cluster-secrets
stringData:
  SECRET_DOMAIN: ENC[AES256_GCM,data:rbJGLQ6AxckOz/9lCYX7K3g=,iv:Wgk79JfE+9YU13WWgtdDAvv/u49AxG1RHsc3KazSwo8=,tag:C9YW7n9H+8VMVEkYs5VGNQ==,type:str]
sops:
  age:
    - recipient: age1apkw8x08jjevajqf39f5g3awkxk3u82c5l6r9y44h0slk9jlds3qvxkcnu
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBVRGVabmpKTERBQy9sMmZX
        UHdRNGRsUS9TbXcybUlpNjRHbWJ3TlJmTlFVCi85bU4rNG9yazgyRk1acXNCNnM3
        bk5wSG0ydXFibXdwTVBzTDlzam16M3cKLS0tIHN2R0YwWmd2Smp4MVhjcEVETjVz
        L2pQdDF4c3pGZEJmUDZhU3hWR0RRZTgKzQ1m7YEgFzcyoO/Z+z1U8tCpU6/DLnqz
        089Paa6bqSe9Ys+bsQzh0p0c1Sjzb0Gcpszg5GmcNLD/v/L0EOG9Vg==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-12-05T01:31:34Z"
  mac: ENC[AES256_GCM,data:UxG6arw2kksO/0K+Bkx4aX/2j1+HGWlrmi2SG8EFNf2c4qohOLo91nqI70kdYPazF4SKELYtBXoxaWHaBPY6ihyhkIxCBUctPekmK4Sc9HzT8qqopUFgzm1+unTBmIdldFe3maLWjYULyeVdf+jlac1QV0dAVORoJbmAqJIsnLo=,iv:zSz5jXPq0s7X7NlQfOHtJoDidhmSFCJuMVt7j/+YBoQ=,tag:vnh4mumxPGuj3rzqf+yQng==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
