apiVersion: v1
kind: Secret
metadata:
  name: github-webhook-token-secret
stringData:
  token: ENC[AES256_GCM,data:A5aNKvIc+24SPM6Q9GcFv2HBvVk2oxqn0D/7hDd1ang=,iv:jNynCm/Lu9xFZt4SFiTZVBtQ+OBfQP+xdviNusE/TQA=,tag:n9x1YgtEjavDZekQOfu7qA==,type:str]
sops:
  age:
    - recipient: age1apkw8x08jjevajqf39f5g3awkxk3u82c5l6r9y44h0slk9jlds3qvxkcnu
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBSQlNmK2hrR29tRmRsS1Rm
        VzBmWHVxb01uZXdySDRjelRUS1M3RzV4MGtnClRjNGptcTlKZDE5cDlPMWJ1VlZl
        T0NmL1dtWmhvNkY2VndYeC9UZjhSQ0EKLS0tIG5tUzdMc3VnSjhMV0FzekxoS01Q
        ck9NaDFPUnNnV0xoejFISUZxeU50ZDQKwlO6PkZXaRNii2T/jAKi+8XrE3u1vyQ/
        qCaduWbuOH7v329eDznE5M+xeUG4+UkziBL4GF4k7VhEzg13w3Ls+g==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-12-05T01:31:34Z"
  mac: ENC[AES256_GCM,data:VygzGtqayknX0OdBgUc1GhymzgW3JofCTU2X8dRl8/gfDjAZFsVp3wsorNhogpn0hRkOrl7AxM6e+Ya4LE8Ok6+tkQ4zN56RaxcXm4yqe5XlcucRlVyeXlbnPCQEEdcV3OSgT3u05dYGu6D/8m3My6pLCuvAGPyDEUmIqglhilc=,iv:CodHRmREiPvZmTWphCqUpQ3j3RZg6j+vE+4cBq5MsYU=,tag:V+6ePOFRSd0dXo6hC883tQ==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
