apiVersion: v1
kind: Secret
metadata:
  name: github-webhook-token-secret
stringData:
  token: ENC[AES256_GCM,data:agy5++uNH9Jj6qiVfCzLlztL+geADdY7DPSm11negqo=,iv:s6BXSvFIa6sDqzAlgftFcnodCPq0oYS/ekLaltQjFqw=,tag:rD+Xz4uG/CS9jBw1i5jeSA==,type:str]
sops:
  age:
    - recipient: age1apkw8x08jjevajqf39f5g3awkxk3u82c5l6r9y44h0slk9jlds3qvxkcnu
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBnQ3ZseEhlMDdsWEFzUlV6
        dEtJaXJDQTV1eStvN2FReDkrY21yUENDRHk4CnhETzFiWGdHaU9RdjJLRDVDcVhk
        N1RILzlEYUE2Um1MSzVFTVV5aTVQZFEKLS0tIE1XZ09lUW85dTFnNjZJZU9Vc0Iy
        UVVYQWxyT0hleGg3ck9QOUMxM3JSeFkKFrP5fwRMCMjfqQcO9ji9gtCUE66vhGOF
        nB+MtKiOcpBt2iodR0wXu3FiMsGhDLQ7qf1fMkgzorHzqo1P0tihyw==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-12-05T00:28:13Z"
  mac: ENC[AES256_GCM,data:4+vSWU+8jvTN3jtYEMzAGsYqWVPgLzCfVAn2PYkBS+b0uZKbbNhBs4+a+M5gTxbzX91VQinLZnXlUU8sjD2a6aYPrTigdPxLa40A0wOo1qhCsw8DlKFoJbsNBOdU9JnieulLWEeHss8/zj9vzK6Xce+Mka/+9VD5hNpvkBtwsTg=,iv:3h+aWJ6jxdcRimkcFmela7vVpkzqjQt2qsBHZE5C45Y=,tag:dyQ5WpBJKDMcW1h71j3g+w==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
