apiVersion: v1
kind: Secret
metadata:
  name: github-webhook-token-secret
stringData:
  token: ENC[AES256_GCM,data:pm5KkGm1QvqTdGMLOB9FGRdZDvdcGmjvyLr1D8k7p48=,iv:p7gmP4Lkn1+MduHgh6wYqwOOdUb+f3MrMeFVeXOSKRI=,tag:DpkD4vIdRKoayVqZDjZ5ZA==,type:str]
sops:
  age:
    - recipient: age1apkw8x08jjevajqf39f5g3awkxk3u82c5l6r9y44h0slk9jlds3qvxkcnu
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBpVXdkTksvSG9vR1VwZW1T
        b25SUkV3eEZTemxWMHZJZHI0SHM1cGpGUkMwCllkbkR3SE5zOGdlWWhrc0M5c1l0
        WEJGSEFwQ0dpN1lRWms3QU1NRlhsWFEKLS0tIEprN2NQUVBtVWtIN01MYnNmQjhV
        UG13TjU3cExrSzVRVDN6czRVbFc5OTgKQwMAIlFMmaudqpdEknKDWTeniiYvpUv2
        dv/hyekiVSDchIap09yl2b/Ko8LoWor+c5/g3RKJ2dxmQXHrMYr5Dg==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-12-05T01:26:55Z"
  mac: ENC[AES256_GCM,data:koe2DTZcXqcpS6MWSgHYXfDGPxR8cQYbO2rX0LA6ZtdP0Qdr11NMEG5o4vrOmVAWqdmMXfIfgx3zEWOfpQUqnusNIGLhQZT0sj8mbreIu+DlNMqEF0UN8DO5iQQjo9gObNknoFr1aLtTeqedAiRPSBDqedSD/yU7bHrjpWXtw7o=,iv:N/lF6ejG5ZYLCpGPle18lfu1lHAHqvQfvBYX9w4Pc3g=,tag:4SxIBnPzVmLSb2POFy8ycQ==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
