apiVersion: v1
kind: Secret
metadata:
  name: cloudflare-tunnel-secret
stringData:
  TUNNEL_TOKEN: ENC[AES256_GCM,data:5eAn4XzDY6qzMh6ZnIdMu/WTAH0ih0ZRygRKKAIrljdAOo3LVwiQbWJXrMC6tXze6s/d7E2Hk82lNehW5kwnzb+U2kwq89uHq24sZnrtvVcLrzp4zDf/hxteyyntgCs9gF3ojRqxgDPrKLIVDGHI3XwOd/Ij7sTm1tKDPDbPzV6X1L242HD9wDqxJQSDI+hz5nOL+9L0tzsQ5E08e+lH7Y/86napFgdHZ7lG0nbtJdUiuBoe,iv:8zX/hf+MyhjG4ROk+z4Wz3gUEKz39oiCVC16UnD0fRw=,tag:jIki+pIIR1LsxQPK5fbA/A==,type:str]
sops:
  age:
    - recipient: age1apkw8x08jjevajqf39f5g3awkxk3u82c5l6r9y44h0slk9jlds3qvxkcnu
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBwZ0w0YVhCVUorVm5YazZD
        d1VQUGY2c1ZzUm90SUJ5UHJEQ0swWWRMc3hZCm4ycFN5aW5yZnhRVkExSWFCZ2Ry
        S3pDYlR1YjdIVTgzOTE5OEhnWjU0SXMKLS0tIE5mWnBwQjUrSnVoUHRLQ1RoVVZD
        TUZwN3hhaXhENDZpUWx5bWgwVzFHeGMKW9C1Pojy6QbSIE4zSJHdVjLYUNWmal2S
        PWz2WyvbsJGtCPAM0q6cx7CRZFbaCOjXbui2gj7KwWUfix57P9aaaQ==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-12-05T00:28:13Z"
  mac: ENC[AES256_GCM,data:XDOWvdYETCiCdRO8YsHGQQx5fc7/44aGP0tBDSm8iGBextPytnLr3wa5Iiht1kSqzUn/jOKCFIGbGGNKHi3PNA/GztZs8NcyVP2JN8L8nM9h6y75q+fyVYylE5cCPYGb0B6EbV3bMrBaawWmzq6DVlYlpcqy+P6LarFSdXdwj1o=,iv:CdyDnzC39cczCxbn8cWGqbOBBuJKFtD7EwgYo6Gqz6c=,tag:RCr+3Rhxkq3htMK9QSmZDA==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
