apiVersion: v1
kind: Secret
metadata:
  name: cloudflare-tunnel-secret
stringData:
  TUNNEL_TOKEN: ENC[AES256_GCM,data:joScnPRYm3usO2ZamRSbw9fn5THWaTPEoRDbw4XjRVU+fGcgIAllPnqpjvNwQSd52q476h5TZc7RgjITss4P/sYqHlSZSKN2nyJOJGeuJF/xZYyv/mBmKU9TRXB0Nbx1MIqnZ1CQtnJz6yVmEWLkLVBiz5gdxPDdj+lqmciSIir8RjsACCiRheuQLKR79MgpMdlOOWYzsrkCEuBLkSclP0hU85A46PlXB/SOZSA/We3wIf/A,iv:66iaI0dvfuzyEL91Wfm8udKh2IEhOLGp0mFCRrKMPiQ=,tag:aLxa05Zb16TSn66bDj03Kw==,type:str]
sops:
  age:
    - recipient: age1apkw8x08jjevajqf39f5g3awkxk3u82c5l6r9y44h0slk9jlds3qvxkcnu
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBoeEM3RFQ5NEJpZG5mNXBG
        TG1tcWE4bG9hcEdPb0tFVzQ0Z1pjbUlYWFRBCjNkQjRjTmsyVG9UL3NNYVZrdmVF
        RGdVRXdvR2JRZ01wbjlheVl6aUdSTzAKLS0tIGpnbFc0aWs4MWMxdWpIV0s4UVBh
        cnVsb2UyVlFUT0tKaWY4dEdFdUpodGsKIAXffbUICpuWFp/272u59c9J0NuR1kEX
        ocxQpksfY4f2Is1NHYJsUTN3s3z7S3oz2vraQdlcqkcVq2I1+sUvkA==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-12-05T01:26:55Z"
  mac: ENC[AES256_GCM,data:mARHzfv+Wp8rOkT6ZrdNXlyVIPejlRLHKkSXpIiuy0qRSfIHJcWFfqztJIMZqbEK0NahqZ3vAmWLOXZLn1fmcCbZ7uA1VAczLNimQU/rRNyvBxxPsEsoI6mVTvEZrYfAHRisah3aUiIkUReNFrOH5m2hCJ+DHiFvURF+z7wZEVg=,iv:0zGCz+ZPU4yJZpa8d7Q9oiqjXL6cNM2wIdM8KO7w8sw=,tag:iJ4FTjZ70Lb2bz3aLuVLGw==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
