apiVersion: v1
kind: Secret
metadata:
  name: cloudflare-tunnel-secret
stringData:
  TUNNEL_TOKEN: ENC[AES256_GCM,data:LKvusQsyAovqKYDZGKuai1wnnUEbt9gpfweDFY8Bdx1x7eebM0IrBOR5Gfd9Wylh0J2bZLsq4Ue8T0M6zMIfHCMpMQuPYIlHJyBMWHI+fOwQYRlJnsKn8RQuLyG2yOCjmbSnk50saGN84wljyrt6LuNdZGuekRnW8UE1c8OCfSBHSOBHnhNE9q8IYgMIuOObj7uobwAAIIGCduCTX/AgjVDFlNnLz+a801OLX0PMDf0EezQB,iv:b0hHYBHjxDrtY6GjBhXMuDzOPxjOAn311iH6f3jwHes=,tag:C1oe7H4Og8V+Tk3Tt+/bVA==,type:str]
sops:
  age:
    - recipient: age1apkw8x08jjevajqf39f5g3awkxk3u82c5l6r9y44h0slk9jlds3qvxkcnu
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBQRUY1K0RxdS9LMml2NjNj
        Q0E4Uk93ZmtUOUIxQUJuR2JNZ0FjZUo5eVQ4Ci9lTmVxakl4LzgvNXdCMDlyNTZN
        Ym1DUTNWejR6c3p6MFNMSUpReEJ1NmcKLS0tIE82UW4yQ2RzcUtSK1VXeDYwVEFu
        QTNCc3hDMFVkYXE4alJxZ2t2Mi9pTmsKfDb0qq90sYzhoEYXLL81ghdZf4e2i6lC
        46k3Uv0fr+ACsh2aixDWEJI1bUgfW1lQT3lZ159h2SmJUGFo36xTrw==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-12-05T01:31:34Z"
  mac: ENC[AES256_GCM,data:B6mdxGHAEkyeiedF02uvy5cGbUYhQOoWH1NhGKRAehi4nXiHTpFsXLp+PmoTi2ySJX0p8AO+eH0gsGvGXj42yoM1XaYn2LJAApxt/dOj1u8vbdH0IKAVPZY+RQzAwUmaQk/heAzZ2wz2kLJW0+3eU9MN+gBhf56VsYXM8xh9nvs=,iv:34HbbAbKmiHhLwXhTNtmB+4m3hl1YJHaK7Niuv39j/Q=,tag:pi6R1rHt7jENBD8L3qhbbw==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
