apiVersion: v1
kind: Secret
metadata:
  name: cert-manager-secret
stringData:
  api-token: ENC[AES256_GCM,data:KVmHx6Wmf/FEkZBOLWXqvKOaGphrgVcwsbYajRLfJR7GuCnehF1MVg==,iv:TyNveQkL5+2ehgOnCEyAcYTqcC5eP1XsuPIAmmaARq4=,tag:/7Bc71TjFCTni6UZTxfugw==,type:str]
sops:
  age:
    - recipient: age1apkw8x08jjevajqf39f5g3awkxk3u82c5l6r9y44h0slk9jlds3qvxkcnu
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBQQ0toNFRjTFZOZkhKQU1S
        VzFGSlo1d3JTQW1DdTg2Y1RSZ0RHUFdBOGtrClYzY3JzY3pkNDhGS3hTRUppVlNB
        UXZDM2s0Y1RON2ZOZ2RqdkJZQzhPQzQKLS0tIFlnMklITmcvRExuN29TMHd3ZWhr
        MThJZjJnZnJsSmhBRjk5aDl4OEMxSkEKV/BKde+IZ0m1fFgyNOw2pxx5YfIRpagZ
        EjcRPy58yP0VLcZd+IQAho5arTkmMq25yg+L0BkXAgA5e5+y7jzFTg==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-12-05T01:31:34Z"
  mac: ENC[AES256_GCM,data:RB+h45eEgOCjcMtvkjgsjtS/kfjGUFIHJm2sCuvTygTZwBh03SVSk47BkvvENS1LC9/e0+4XrFMrMMcHLd3dAVeR2561MRx1RYKoleT/B3u7fcNbw6R6fLLM0M6iV/6PFZ/1Vh3l1u0XM+70Gg+t+WbvaVVWZ6gR9tGMJ0I3Ziw=,iv:00ELHtUAkbWdpMsRRjv2ZDLwPADp/q58ifcKslFKs9A=,tag:FrzJ6QFXKvZ06/a5JkVspg==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
