apiVersion: v1
kind: Secret
metadata:
  name: cert-manager-secret
stringData:
  api-token: ENC[AES256_GCM,data:P4+Thu85niUTkiUdgX4TpUwtI/Nwv94VtUjkUzp9GMq2P1qWPX0fEQ==,iv:7S4B5JlRIEuj+KuJPshaFt33tnDwdYcVabEtbvsIPI4=,tag:DIeD6oXEYr4Pft8WX3npqA==,type:str]
sops:
  age:
    - recipient: age1apkw8x08jjevajqf39f5g3awkxk3u82c5l6r9y44h0slk9jlds3qvxkcnu
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBVYThZVHlIQ1d3UURQdmQ2
        SHhLS3ErTXBma0xHakE4MDJrcEY5clkxcUhrCmJqYlk3ZDA5bVdBdEJiMTRTSmZZ
        Snc3Z2UxMG5TeFJJQlRBMTZaSDFUcGMKLS0tIGdCWC8xVk9FM3VGYkNJeFQ2cndK
        RG0wNlhCb1loSTU1LzZ3NE9vM1RDVVEKPJrcNVXlI0GIf9PQMLaCh1+Dmzv7FYV9
        PGoEPle5LiXdbXV1ORhavkTBcZ0560PJYsmnmT8YANXS3FLl19+hew==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-12-05T00:28:13Z"
  mac: ENC[AES256_GCM,data:6YVurhHlvOLNgOPwYnYwXv7OvD4WR+BnckX/DIQVWDrnPKb2mt0zLjgSIxrGgLiS8qY8I3XC1LZkF1f1o1CptzgFDcFdkDP3ve5Jt1w9mpxlkk0L5tgPDJ4h7RWhgixhXXmc9pp5DC/Cn0X3hAz5pHqlsz4oSxgr2SUu0+gtySA=,iv:btqKxGWtqUM537C580C8A0IuvYxEbMxAJ276LvoHFS8=,tag:wf9v7widBn9vt0kcEQNOnw==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
