apiVersion: v1
kind: Secret
metadata:
  name: cert-manager-secret
stringData:
  api-token: ENC[AES256_GCM,data:YQRK83ucdQ7V5ZtzlxqMhmDoQGpi6K8CpIpPbC1sxcr3tOyPZNFYwQ==,iv:liljmqN4doUO+qhzqIf1dl2HGbV91cmVMA7dx7Z9Ros=,tag:cq6cpLyyeVp432xer3EL7Q==,type:str]
sops:
  age:
    - recipient: age1apkw8x08jjevajqf39f5g3awkxk3u82c5l6r9y44h0slk9jlds3qvxkcnu
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB2N1dpZkJkUGdFTkxZRGpa
        V1hNS3BEeHpQMnhsaUNqR0pzMG1tMk5xaGtrCks3SHRXcTVCcE5NVEptcWYxQkJt
        UkQvOE5mSktzRHcwWVlpcEJ0NTJFU2cKLS0tIERMc1JsVmRMeEQ2d2lwOW1nS2Z1
        aWFvUCtodEp3clpyNVVESWtCN3Jyb2MKJEsJR+bQwogJuNraMHGSc1ln2n8Z48CF
        Yf5r81yYn+3hHcq2Cn9s4DysOaEb83F7d5cAlMgHSea0C+iex8apeg==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-12-05T01:26:55Z"
  mac: ENC[AES256_GCM,data:YuDZIf3BKPzVDrncOis2+Lks05zhNiIEw2mNAVWNi2ZoXaMG3tvuiR/IbaGVlBBXtDe3BPgcEMW+h45KZGBxwfzDhghmPd8ENAJNU8R88zAI0BPkvYy10TWMNWjUs4hKUc4nyE7nmSC+4/+J9pbkn5dgHmy7OldcozqKHKz38kM=,iv:VYh0LQ+sYwtZlG6TINpsaASFrly15hHxDDJwVaGZKXY=,tag:kIxuhwVaciAdQ2ODCineLQ==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
