---
clusterName: kubernetes

talosVersion: "${talosVersion}"
kubernetesVersion: "${kubernetesVersion}"

endpoint: https://192.168.0.207:6443
additionalApiServerCertSans: &sans
  - "127.0.0.1"
  - "192.168.0.207"
additionalMachineCertSans: *sans

clusterPodNets: ["10.42.0.0/16"]
clusterSvcNets: ["10.43.0.0/16"]

# Disable built-in CNI to use Cilium
cniConfig:
  name: none

nodes:
  - hostname: "k3s-talos-1"
    ipAddress: "192.168.0.201"
    installDisk: "/dev/sda"
    machineSpec:
      secureboot: false
    talosImageURL: factory.talos.dev/installer/376567988ad370138ad8b2698212367b8edcb69b5fd68c80be1f2ec7d603b4ba
    controlPlane: true
    networkInterfaces:
      - deviceSelector:
          hardwareAddr: "bc:24:11:dd:a8:42"
        dhcp: false
        addresses:
          - "192.168.0.201/24"
        routes:
          - network: "0.0.0.0/0"
            gateway: "192.168.1.3"
        mtu: 1500
        vip:
          ip: "192.168.0.207"
  - hostname: "k3s-talos-2"
    ipAddress: "192.168.0.202"
    installDisk: "/dev/sda"
    machineSpec:
      secureboot: false
    talosImageURL: factory.talos.dev/installer/376567988ad370138ad8b2698212367b8edcb69b5fd68c80be1f2ec7d603b4ba
    controlPlane: true
    networkInterfaces:
      - deviceSelector:
          hardwareAddr: "bc:24:11:25:4c:96"
        dhcp: false
        addresses:
          - "192.168.0.202/24"
        routes:
          - network: "0.0.0.0/0"
            gateway: "192.168.1.3"
        mtu: 1500
        vip:
          ip: "192.168.0.207"
  - hostname: "k3s-talos-3"
    ipAddress: "192.168.0.203"
    installDisk: "/dev/sda"
    machineSpec:
      secureboot: false
    talosImageURL: factory.talos.dev/installer/376567988ad370138ad8b2698212367b8edcb69b5fd68c80be1f2ec7d603b4ba
    controlPlane: true
    networkInterfaces:
      - deviceSelector:
          hardwareAddr: "bc:24:11:11:9c:5e"
        dhcp: false
        addresses:
          - "192.168.0.203/24"
        routes:
          - network: "0.0.0.0/0"
            gateway: "192.168.1.3"
        mtu: 1500
        vip:
          ip: "192.168.0.207"
  - hostname: "k3s-talos-4"
    ipAddress: "192.168.0.204"
    installDisk: "/dev/sda"
    machineSpec:
      secureboot: false
    talosImageURL: factory.talos.dev/installer/376567988ad370138ad8b2698212367b8edcb69b5fd68c80be1f2ec7d603b4ba
    controlPlane: true
    networkInterfaces:
      - deviceSelector:
          hardwareAddr: "bc:24:11:b1:59:c9"
        dhcp: false
        addresses:
          - "192.168.0.204/24"
        routes:
          - network: "0.0.0.0/0"
            gateway: "192.168.1.3"
        mtu: 1500
        vip:
          ip: "192.168.0.207"
  - hostname: "k3s-talos-5"
    ipAddress: "192.168.0.205"
    installDisk: "/dev/sda"
    machineSpec:
      secureboot: false
    talosImageURL: factory.talos.dev/installer/376567988ad370138ad8b2698212367b8edcb69b5fd68c80be1f2ec7d603b4ba
    controlPlane: true
    networkInterfaces:
      - deviceSelector:
          hardwareAddr: "bc:24:11:87:9c:34"
        dhcp: false
        addresses:
          - "192.168.0.205/24"
        routes:
          - network: "0.0.0.0/0"
            gateway: "192.168.1.3"
        mtu: 1500
        vip:
          ip: "192.168.0.207"
  - hostname: "k3s-talos-6"
    ipAddress: "192.168.0.206"
    installDisk: "/dev/sda"
    machineSpec:
      secureboot: false
    talosImageURL: factory.talos.dev/installer/376567988ad370138ad8b2698212367b8edcb69b5fd68c80be1f2ec7d603b4ba
    controlPlane: true
    networkInterfaces:
      - deviceSelector:
          hardwareAddr: "bc:24:11:d1:0d:75"
        dhcp: false
        addresses:
          - "192.168.0.206/24"
        routes:
          - network: "0.0.0.0/0"
            gateway: "192.168.1.3"
        mtu: 1500
        vip:
          ip: "192.168.0.207"

# Global patches
patches:
  - "@./patches/global/machine-files.yaml"
  - "@./patches/global/machine-kubelet.yaml"
  - "@./patches/global/machine-network.yaml"
  - "@./patches/global/machine-sysctls.yaml"
  - "@./patches/global/machine-time.yaml"

# Controller patches
controlPlane:
  patches:
    - "@./patches/controller/cluster.yaml"

